server:
  port: 8081
spring:
  application:
    name: hotel-api-gateway
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"
    gateway:
      routes:
        - id: guest-service
          #          uri: lb://guest-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/guest/**
          filters:
            - CustomFilter1

        - id: hotel-service
          #          uri: lb://HOTEL-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/api/hotel/**
          filters:
            - CustomFilter1

        - id: reservation-service
        #          uri: lb://reservation-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/reservation/**
          filters:
            - CustomFilter1

        - id: authentication-service
          #          uri: lb://authentication-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/authentication/**
          filters:
            - CustomFilter1
