server:
  port: 8084
spring:
  application:
    name: reservation-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: password
    flyway:
      schemas: reservation
      user: postgres
      password: password
      enabled: true
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      discovery:
        instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"

internal-api:
  hotel-service:
    name: hotel-service
    path: /api/hotel

resilience4j:
  circuitbreaker:
    instances:
      circuit_1:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always