server:
  port: 8083
spring:
  application:
    name: hotel-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: password
    flyway:
      schemas: hotel
      user: postgres
      password: password
      enabled: true
  cloud:
    bootstrap:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#  shouldUseDns: false
#  instance:
#    preferIpAddress: true
#    instance-id: "EPVNHOCW0052.princeton.epam.com:${spring.application.name}:${random.int[1,999999]}"

#spring:
#  cloud:
#    bootstrap:
#      enabled: true