server:
  port: 8083
spring:
  application:
    name: hotel-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: password
    flyway:
      schemas: hotel
      user: postgres
      password: password
      enabled: true
  cloud:
    bootstrap:
      enabled: true
    consul:
      discovery:
        ip-address: EPVNHOCW0052.mshome.net
        preferIpAddress: true
        instance-id: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s

